[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
voting = "5Fmz3ZSRyEQki4UpfARGigCTrK3sXfkJxSBxURnUjTxD"

[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "devnet"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[provider]
cluster = "localnet"   # change from "devnet"
wallet = "~/.config/solana/id.json"


[programs.localnet]
voting = "5Fmz3ZSRyEQki4UpfARGigCTrK3sXfkJxSBxURnUjTxD"   
